name: aws_s3_plugin
description: aws_s3_plugin.
version: 0.0.1
repository: https://github.com/FaKenKoala/aws_s3_plugin/tree/main/aws_s3_plugin

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  aws_s3_android:
    path: ../aws_s3_android
  aws_s3_ios:
    path: ../aws_s3_ios
  aws_s3_platform_interface:
    path: ../aws_s3_platform_interface
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: aws_s3_android
      ios:
        default_package: aws_s3_ios
