name: aws_s3_ios
description: ios implementation of aws_s3_plugin.
version: 0.0.1
repository: https://github.com/FakenKoala/aws_s3_plugin/tree/main/aws_s3_ios

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  aws_s3_platform_interface:
    path: ../aws_s3_platform_interface
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    implements: aws_s3_plugin
    platforms:
      ios:
        pluginClass: AwsS3Plugin


